### ISSUE TITLE
Runbook steps that have a worker pool variable are also setting the worker pool id

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusSolutionsEngineering/OctopusTerraformExport#14]
### Octopus version

2024.2.4248

### Octoterra version

latest

### What happened

Octoterra is generating a runbook process using both a worker pool id and a worker pool variable. This fails when trying to apply the terraform to create the project in a new space.

I loaded the process and looked at the output from the API calls, and it doesn't seem like the worker pool id is actually set when returned from the API so it's unclear how it's getting into Octoterra's output

### Octoterra log output

https://demo.octopus.app/app#/Spaces-178/projects/octopub-yaml-serializer/operations/runbooks/Runbooks-7736/snapshots/RunbookSnapshots-19729/runs/RunbookRuns-160721?activeTab=taskLog&level=verbose

### Reproduction steps

Replication: https://demo.octopus.app/app#/Spaces-178/projects/octopub-yaml-serializer/operations/runbooks/Runbooks-7736/runslist

### More Information

![image](https://github.com/OctopusSolutionsEngineering/OctopusTerraformExport/assets/1571799/c6c5e8db-4c0d-42e1-a7a8-bac18830a3b5)

**Comment by mcasperson** [comment]
Old HCL:
![old](https://github.com/OctopusSolutionsEngineering/OctopusTerraformExport/assets/160104/5421b56d-d829-40aa-be46-65055dd43d5a)

New HCL:
![new](https://github.com/OctopusSolutionsEngineering/OctopusTerraformExport/assets/160104/5e4435b4-815b-4cfb-8ccf-3e65af04d6b0)
