### ISSUE TITLE
Add support for external feed and scheduled triggers

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusSolutionsEngineering/OctopusTerraformExport#19]
### Octopus version

2024.2.5350

### Octoterra version

latest

### What happened

The TF provider supports the other project trigger types now!

https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/project_scheduled_trigger

### Octoterra log output

N/a

### Reproduction steps

N/a

**Comment by mcasperson** [comment]
Schedule trigger support was added with https://github.com/OctopusSolutionsEngineering/OctopusTerraformExport/pull/21

**Comment by mcasperson** [comment]
Feed trigger supported added with https://github.com/OctopusSolutionsEngineering/OctopusTerraformExport/pull/22
