### ISSUE TITLE
Sensitive project template can't be exported

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusSolutionsEngineering/OctopusTerraformExport#2]
[Link to error](https://demo.octopus.app/app#/Spaces-178/projects/retail-project-serializer/operations/runbooks/Runbooks-5423/snapshots/RunbookSnapshots-7596/runs/RunbookRuns-120757?tasklineid=0%2FServerTasks-498150_GTB59B8DPW%2F91f672bd17d54f4fb3f0628f713fec23%2F69d40d0f28a7478cbcb155d5706e7d5e&activeTab=taskLog)

> json: cannot unmarshal object into Go struct field Template.Items.Templates.DefaultValue of type string

**Comment by mcasperson** [comment]
The cause of this error was that the default value returned by the API can either be a string or an object capturing the details of a sensitive variable. Octoterra assumed the response was a string though, and failed to serialise a sensitive value.
