### ISSUE TITLE
Not generating GitCredential terraform resource when step package is a git repo

### ISSUE THREAD

**Issue by twerthi** [OctopusSolutionsEngineering/OctopusTerraformExport#31]
### Octopus version

2024.2.9409

### Octoterra version

0.1.1284

### What happened

On database backed projects with steps that use a git repo for the package that uses a Library GitCredential, Octoterra doesn't seem to create a GitCredential Terraform resource.  This results in the error below as well as a blank entry for the GitCredential dependency

```
      git_dependency {
        repository_uri      = "https://github.com/twerthi/Octopub.git"
        default_branch      = "main"
        git_credential_type = "Library"
        git_credential_id   = ""
      }

```

### Octoterra log output

error   Failed to resolve GitCredentials-21 of type Git-Credentials

### Reproduction steps

Create a deployment process that uses a Git Credential from the Library.  The exported step will have the blank for the GitCredentials and you'll receive the above error.

**Comment by mcasperson** [comment]
The issue here is that there is a link between steps that consume files from Git and git credentials. This link was not traversed, so the Git Credential object was not included in an output.
