### ISSUE TITLE
Unable to export default space

### ISSUE THREAD

**Issue by drewfreyling** [OctopusSolutionsEngineering/OctopusTerraformExport#32]
### Octopus version

2023.2

### Octoterra version

0.1.1292+run1304-attempt1

### What happened

Can't export the default space

### Octoterra log output

2024-09-09T11:25:52.095+1000	info	Runbook Process: RunbookProcess-Runbooks-761
2024-09-09T11:25:52.095+1000	error	json: cannot unmarshal object into Go struct field ProjectVariable.ProjectVariables.Variables of type string

### Reproduction steps

./octoterra \
    -url xxx \
    -space Default \
    -apiKey yyy \
    -dest /tmp/octoexport

**Comment by mcasperson** [comment]
@drewfreyling Are you able to attach a screenshot of the project variable page and the tenant variables? That will help us reproduce the issue, as it appears to be related to the tenant variables associated with a project.

**Comment by mcasperson** [comment]
@drewfreyling Can you also try rerunning the export with version 0.1.1294+run1307-attempt1. This new version has more logging for json unmarshalling errors.

**Comment by mcasperson** [comment]
The issue was secret tenant variables. The underlying JSON looked like this:

```
"Variables": {
  "Environments-860": {
    "2a95e072-2966-41c2-9869-55eea704d819": {
      "HasValue": true,
      "NewValue": null,
      "Hint": null
    }
  }
}
```

Secret variables are returned as an object defining the state, but not the value, of a secret. Octoterra was trying to serialise this into an object the expected a string assuming variables looked like this:

```
"Variables": {
  "Environments-858": {
    "41c2653d-3ec9-48dc-aedc-a2b55c8d9f51": "random-quotes-#{Tenant.Key}-#{RandomQuotes.Environment}"
  },
  "Environments-859": {},
  "Environments-860": {}
}
```
